version: '3.8'
services:
   auto-api:
      build: .
      ports:
         - 8080:8080
         - 61616:61616
      depends_on:
         - db
      environment:
         DB_HOST_NAME: db
         DB_PORT: 5432
         DB_NAME: postgres
         DB_USER: postgres
         DB_PASSWORD: root
   db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
         POSTGRES_DB: postgres
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: root
   nginx:
      image: auto-front
      ports:
         - 80:80
      
   